-- SBBall Postgres (Neon) schema.
-- Ported from the original SQLite schema in sbball-server/src/server.ts.
--
-- NOTE ON CASING: the frontend reads camelCase keys straight off `SELECT *`
-- results (e.g. playerName, twosAttempted, snapshotPts). Postgres folds
-- unquoted identifiers to lowercase, so every camelCase column (and the
-- reserved word "desc") is double-quoted to preserve its exact casing.
--
-- IDs use GENERATED BY DEFAULT AS IDENTITY so the migration script can insert
-- the original SQLite ids explicitly; the sequences are bumped past MAX(id)
-- afterward so new inserts continue cleanly.

CREATE TABLE IF NOT EXISTS players (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "playerName" TEXT,
  jersey       INTEGER,
  position     TEXT,
  "secPosition" TEXT,
  height       TEXT,
  nickname     TEXT,
  weight       INTEGER
);

CREATE TABLE IF NOT EXISTS awards (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT,
  "winnerName" TEXT,
  "timesWon"   INTEGER
);

CREATE TABLE IF NOT EXISTS games (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team1         TEXT,
  team2         TEXT,
  "playerCount" INTEGER,
  winner        INTEGER,
  date          TEXT,
  -- Playoff series number (1-based). Regular-season games stay 1.
  series        INTEGER DEFAULT 1
);

-- Non-shooting counting stats (ast/blk/defReb/fouls/offReb/stl/tov) are
-- DOUBLE PRECISION, not INTEGER: the "average fill" feature backfills them with
-- career averages, which are fractional. float8 also deserializes to a JS number
-- (unlike numeric, which would come back as a string and break frontend math).
CREATE TABLE IF NOT EXISTS stats (
  id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ast               DOUBLE PRECISION,
  blk               DOUBLE PRECISION,
  "defReb"          DOUBLE PRECISION,
  fouls             DOUBLE PRECISION,
  "playerName"      TEXT,
  "offReb"          DOUBLE PRECISION,
  stl               DOUBLE PRECISION,
  threes            INTEGER,
  "threesAttempted" INTEGER,
  tov               DOUBLE PRECISION,
  twos              INTEGER,
  "twosAttempted"   INTEGER,
  rating            DOUBLE PRECISION,
  "gameId"          INTEGER,
  minutes           DOUBLE PRECISION,
  "plusMinus"       INTEGER
);

CREATE TABLE IF NOT EXISTS playoff_stats (
  id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ast               DOUBLE PRECISION,
  blk               DOUBLE PRECISION,
  "defReb"          DOUBLE PRECISION,
  fouls             DOUBLE PRECISION,
  "playerName"      TEXT,
  "offReb"          DOUBLE PRECISION,
  stl               DOUBLE PRECISION,
  threes            INTEGER,
  fts               INTEGER,
  "threesAttempted" INTEGER,
  tov               DOUBLE PRECISION,
  twos              INTEGER,
  "twosAttempted"   INTEGER,
  rating            DOUBLE PRECISION,
  "gameId"          INTEGER,
  minutes           DOUBLE PRECISION,
  "plusMinus"       INTEGER
);

CREATE TABLE IF NOT EXISTS game_feed (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rel_id           INTEGER,
  "playerName"     TEXT,
  "desc"           TEXT,
  score            TEXT,
  "snapshotPts"    INTEGER,
  "snapshotAst"    INTEGER,
  "snapshotOffReb" INTEGER,
  "snapshotDefReb" INTEGER,
  "snapshotBlk"    INTEGER,
  "snapshotStl"    INTEGER,
  "gameId"         INTEGER,
  -- Wall-clock instant the play was recorded (NULL for pre-feature games).
  "occurredAt"     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS game_feed2 (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rel_id           INTEGER,
  "playerName"     TEXT,
  "desc"           TEXT,
  score            TEXT,
  "snapshotPts"    INTEGER,
  "snapshotAst"    INTEGER,
  "snapshotOffReb" INTEGER,
  "snapshotDefReb" INTEGER,
  "snapshotBlk"    INTEGER,
  "snapshotStl"    INTEGER,
  "gameId"         INTEGER,
  -- Wall-clock instant the play was recorded (NULL for pre-feature games).
  "occurredAt"     TIMESTAMPTZ
);

-- Backfill for existing databases (idempotent).
ALTER TABLE game_feed  ADD COLUMN IF NOT EXISTS "occurredAt" TIMESTAMPTZ;
ALTER TABLE game_feed2 ADD COLUMN IF NOT EXISTS "occurredAt" TIMESTAMPTZ;

-- Helpful indexes for the stat aggregation queries.
CREATE INDEX IF NOT EXISTS stats_gameid_idx ON stats ("gameId");
CREATE INDEX IF NOT EXISTS playoff_stats_gameid_idx ON playoff_stats ("gameId");
CREATE INDEX IF NOT EXISTS stats_player_idx ON stats ("playerName");
CREATE INDEX IF NOT EXISTS playoff_stats_player_idx ON playoff_stats ("playerName");
CREATE INDEX IF NOT EXISTS game_feed_gameid_idx ON game_feed ("gameId");
CREATE INDEX IF NOT EXISTS game_feed2_gameid_idx ON game_feed2 ("gameId");
